export const ecuador = [
  {
    provincia: "Azuay",
    cantones: [
      "Cuenca",
      "Girón",
      "Gualaceo",
      "Nabón",
      "Paute",
      "Pucará",
      "San Fernando",
      "Santa Isabel",
      "Sigsig",
      "Oña",
      "Chordeleg",
      "El Pan",
      "Sevilla de Oro",
      "Guachapala",
      "Camilo Ponce Enríquez",
    ],
  },
  {
    provincia: "Bolívar",
    cantones: [
      "Guaranda",
      "Chillanes",
      "Chimbo",
      "Echeandía",
      "San Miguel",
      "Caluma",
      "Las Naves",
    ],
  },
  {
    provincia: "Cañar",
    cantones: [
      "Azogues",
      "Biblián",
      "Cañar",
      "La Troncal",
      "El Tambo",
      "Déleg",
      "Suscal",
    ],
  },
  {
    provincia: "Carchi",
    cantones: [
      "Tulcán",
      "Bolívar",
      "Espejo",
      "Mira",
      "Montúfar",
      "San Pedro de Huaca",
    ],
  },
  {
    provincia: "Chimborazo",
    cantones: [
      "Riobamba",
      "Alausí",
      "Colta",
      "Chambo",
      "Chunchi",
      "Guamote",
      "Guano",
      "Pallatanga",
      "Penipe",
      "Cumandá",
    ],
  },
  {
    provincia: "Cotopaxi",
    cantones: [
      "Latacunga",
      "La Maná",
      "Pangua",
      "Pujilí",
      "Salcedo",
      "Saquisilí",
      "Sigchos",
    ],
  },
  {
    provincia: "El Oro",
    cantones: [
      "Machala",
      "Arenillas",
      "Atahualpa",
      "Balsas",
      "Chilla",
      "El Guabo",
      "Huaquillas",
      "Las Lajas",
      "Marcabelí",
      "Pasaje",
      "Piñas",
      "Portovelo",
      "Santa Rosa",
      "Zaruma",
    ],
  },
  {
    provincia: "Esmeraldas",
    cantones: [
      "Esmeraldas",
      "Atacames",
      "Eloy Alfaro",
      "Muisne",
      "Quinindé",
      "Rioverde",
      "San Lorenzo",
    ],
  },
  {
    provincia: "Galápagos",
    cantones: ["San Cristóbal", "Santa Cruz", "Isabela"],
  },
  {
    provincia: "Guayas",
    cantones: [
      "Guayaquil",
      "Alfredo Baquerizo Moreno",
      "Balao",
      "Balzar",
      "Colimes",
      "Daule",
      "Durán",
      "El Empalme",
      "El Triunfo",
      "Milagro",
      "Naranjal",
      "Naranjito",
      "Palestina",
      "Pedro Carbo",
      "Playas",
      "Salitre",
      "Samborondón",
      "Santa Lucía",
      "Simón Bolívar",
      "Yaguachi",
      "Lomas de Sargentillo",
      "Nobol",
      "General Antonio Elizalde",
      "Isidro Ayora",
    ],
  },
  {
    provincia: "Imbabura",
    cantones: [
      "Ibarra",
      "Antonio Ante",
      "Cotacachi",
      "Otavalo",
      "Pimampiro",
      "Urcuquí",
    ],
  },
  {
    provincia: "Loja",
    cantones: [
      "Loja",
      "Calvas",
      "Catamayo",
      "Celica",
      "Chaguarpamba",
      "Espíndola",
      "Gonzanamá",
      "Macará",
      "Paltas",
      "Puyango",
      "Saraguro",
      "Sozoranga",
      "Zapotillo",
      "Olmedo",
    ],
  },
  {
    provincia: "Los Ríos",
    cantones: [
      "Babahoyo",
      "Baba",
      "Buena Fe",
      "Mocache",
      "Montalvo",
      "Palenque",
      "Puebloviejo",
      "Quevedo",
      "Quinsaloma",
      "Urdaneta",
      "Valencia",
      "Ventanas",
      "Vinces",
    ],
  },
  {
    provincia: "Manabí",
    cantones: [
      "Portoviejo",
      "Bolívar",
      "Chone",
      "El Carmen",
      "Flavio Alfaro",
      "Jipijapa",
      "Junín",
      "Manta",
      "Montecristi",
      "Paján",
      "Pichincha",
      "Rocafuerte",
      "Santa Ana",
      "Sucre",
      "Tosagua",
      "24 de Mayo",
      "Pedernales",
      "Olmedo",
      "Puerto López",
      "Jama",
      "Jaramijó",
      "San Vicente",
    ],
  },
  {
    provincia: "Morona Santiago",
    cantones: [
      "Morona",
      "Gualaquiza",
      "Limón Indanza",
      "Palora",
      "Santiago",
      "Sucúa",
      "Huamboya",
      "San Juan Bosco",
      "Taisha",
      "Logroño",
      "Pablo Sexto",
      "Tiwintza",
    ],
  },
  {
    provincia: "Napo",
    cantones: [
      "Tena",
      "Archidona",
      "El Chaco",
      "Quijos",
      "Carlos Julio Arosemena Tola",
    ],
  },
  {
    provincia: "Orellana",
    cantones: [
      "Francisco de Orellana",
      "Aguarico",
      "La Joya de los Sachas",
      "Loreto",
    ],
  },
  {
    provincia: "Pastaza",
    cantones: ["Pastaza", "Mera", "Santa Clara", "Arajuno"],
  },
  {
    provincia: "Pichincha",
    cantones: [
      "Quito",
      "Cayambe",
      "Mejía",
      "Pedro Moncayo",
      "Rumiñahui",
      "San Miguel de los Bancos",
      "Pedro Vicente Maldonado",
      "Puerto Quito",
    ],
  },
  {
    provincia: "Santa Elena",
    cantones: ["Santa Elena", "La Libertad", "Salinas"],
  },
  {
    provincia: "Santo Domingo de los Tsáchilas",
    cantones: ["Santo Domingo", "La Concordia"],
  },
  {
    provincia: "Sucumbíos",
    cantones: [
      "Lago Agrio",
      "Gonzalo Pizarro",
      "Putumayo",
      "Shushufindi",
      "Sucumbíos",
      "Cascales",
      "Cuyabeno",
    ],
  },
  {
    provincia: "Tungurahua",
    cantones: [
      "Ambato",
      "Baños",
      "Cevallos",
      "Mocha",
      "Patate",
      "Pelileo",
      "Píllaro",
      "Quero",
      "Tisaleo",
    ],
  },
  {
    provincia: "Zamora Chinchipe",
    cantones: [
      "Zamora",
      "Chinchipe",
      "Nangaritza",
      "Yacuambi",
      "Yantzaza",
      "El Pangui",
      "Centinela del Cóndor",
      "Palanda",
      "Paquisha",
    ],
  },
];
